puts "Start seeding...."
    User.destroy_all
    Course.destroy_all
    Announcement.destroy_all
    CourseSession.destroy_all

    user1 = User.create(username: "admin", email: "admin@gmail.com", password_digest: "password", role: "instructor")
    user2 = User.create(username: "student", email: "student@gmail.com", password_digest: "protection", role: "student")

    course1 = Course.create(course_name: "Software Engineering", description: "Software engineering is the branch of computer science that deals with the design, development, testing, and maintenance of software applications. Software engineers apply engineering principles and knowledge of programming languages to build software solutions for end users.")
    course2 = Course.create(course_name: "Mobile Application Development", description: "Mobile app development is the act or process by which a mobile app is developed for mobile devices, such as personal digital assistants, enterprise digital assistants or mobile phones. These software applications are designed to run on mobile devices, such as a smartphone or tablet computer.")
    course3 = Course.create(course_name: "Data Science", description: "Data science is the domain of study that deals with vast volumes of data using modern tools and techniques to find unseen patterns, derive meaningful information, and make business decisions. Data science uses complex machine learning algorithms to build predictive models. The data used for analysis can come from many different sources and presented in various formats.")
    course4 = Course.create(course_name: "Hardware Engineering", description: "Hardware engineering is the field of designing, developing, testing and producing physical computer systems. Hardware engineers are typically detail-oriented and have extensive knowledge about all physical components of a computer system.")
    course5 = Course.create(course_name: "Networking", description: "Networking, also known as computer networking, is the practice of transporting and exchanging data between nodes over a shared medium in an information system. Networking comprises not only the design, construction and use of a network, but also the management, maintenance and operation of the network infrastructure, software and policies.")

    announcement1 = Announcement.create(title: "Welcome Message", content:"Welcome to the Highway School of Technology. We shall equip you with knowledge to tackle your dream job and make it in life.")
    announcement2 = Announcement.create(title: "Google Developer Groups", content:"GDG is open and volunteer geek community who create exciting projects and share experience about Google technologies with passion.")

    course_session1 = CourseSession.create(course_id: 1, session_name: "Introduction to Programming 1", date: "Date: 2023-01-16", time: "8.00am-10.00am", invitation_link: "https://meet.google.com/bgx-ddmb-sfq", description: "Programming is writing computer code to create a program, to solve a problem. Programs are created to implement algorithms. Algorithms can be represented as pseudocode or a flowchart, and programming is the translation of these into a computer program. To tell a computer to do something, a program must be written to tell it exactly what to do and how to do it. If an algorithm has been designed, the computer program will follow this algorithm, step-by-step, which will tell the computer exactly what it should do.")
    course_session2 = CourseSession.create(course_id: 2, session_name: "Introduction to Programming 2", date: "Date: 2023-01-16", time: "11.00am-1.00pm", invitation_link: "https://meet.google.com/bgx-ddmb-sfq", description: "Programming is writing computer code to create a program, to solve a problem. Programs are created to implement algorithms. Algorithms can be represented as pseudocode or a flowchart, and programming is the translation of these into a computer program. To tell a computer to do something, a program must be written to tell it exactly what to do and how to do it. If an algorithm has been designed, the computer program will follow this algorithm, step-by-step, which will tell the computer exactly what it should do.")
    course_session3 = CourseSession.create(course_id: 5, session_name: "Introduction to Networking", date: "Date: 2023-01-17", time: "10.00am-12.00pm", invitation_link: "https://meet.google.com/bgx-ddmb-sfq", description: "Networking, also known as computer networking, is the practice of transporting and exchanging data between nodes over a shared medium in an information system. Networking comprises not only the design, construction and use of a network, but also the management, maintenance and operation of the network infrastructure, software and policies. Computer networking enables devices and endpoints to be connected to each other on a local area network (LAN) or to a larger network, such as the internet or a private wide area network (WAN). This is an essential function for service providers, businesses and consumers worldwide to share resources, use or offer services, and communicate. Networking facilitates everything from telephone calls to text messaging to streaming video to the internet of things (IoT).")
    course_session4 = CourseSession.create(course_id: 1, session_name: "Object Oriented Programming", date: "Date: 2023-01-18", time: "11.00am-1.00pm", invitation_link: "https://meet.google.com/bgx-ddmb-sfq", description: "Object-oriented programming, or OOP, is an approach to problem solving where all computations are carried out using objects. An object is a component of a program that knows how to perform certain actions and how to interact with other elements of the program. Objects are the basic units of object-oriented programming. A simple example of an object would be a person. Logically, you would expect a person to have a name. This would be considered a property of the person. You could also expect a person to be able to do something, such as walking or driving. This would be considered a method of the person.")
    course_session5 = CourseSession.create(course_id: 3, session_name: "Introduction to Data Science", date: "Date: 2023-01-16", time: "2.00am-4.00pm", invitation_link: "https://meet.google.com/bgx-ddmb-sfq", description: "Data Science is the area of study which involves extracting insights from vast amounts of data using various scientific methods, algorithms, and processes. It helps you to discover hidden patterns from the raw data. The term Data Science has emerged because of the evolution of mathematical statistics, data analysis, and big data. Data Science is an interdisciplinary field that allows you to extract knowledge from structured or unstructured data. Data science enables you to translate a business problem into a research project and then translate it back into a practical solution.")

    comment1 = Comment.create(content: "This was a very interesting session.", user_id: 2, course_session_id: 1)
    comment2 = Comment.create(content: "This was a very interesting session.", user_id: 2, course_session_id: 2)
    comment3 = Comment.create(content: "Glad you enjoyed the session.", user_id: 1, course_session_id: 1)
    comment4 = Comment.create(content: "This was a very interesting session.", user_id: 2, course_session_id: 3)
    comment5 = Comment.create(content: "You can go back and do more research on this topic.", user_id: 1, course_session_id: 4)
    comment6 = Comment.create(content: "This one was a bit mbadala.", user_id: 2, course_session_id: 4)
    comment7 = Comment.create(content: "This was a very interesting session.", user_id: 2, course_session_id: 5)
puts "Done seeding."